- name: Proxmox stuff
  hosts: all  
  tasks:
    - name: Check if template is defined and not empty
      assert:
        that:
          - template is defined
          - template | length > 0
        fail_msg: "template is mandatory and cannot be empty. try again with parameter -e template=<template_name> on the ansible-playbook command"
      when: template is not defined or template | length == 0

    - set_fact:
        vm_name: "{{ template }}-instance-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=2') }}"

    - name: create vm
      proxmox_kvm:
        api_user    : "{{ ansible_user }}"
        api_password: "{{ ansible_password }}"
        api_host    : "{{ inventory_hostname }}"
        clone       : "{{ template }}"  # The VM source
        name        : "{{ vm_name }}"  # The target VM name
        node        : home
        storage     : local-lvm
        format      : qcow2
        timeout     : 500  # Note: The task can take a while. Adapt depending on the time it takes to clone the VM.

    - name: start vm
      proxmox_kvm:
        api_user: "{{ ansible_user }}"
        api_password: "{{ ansible_password }}"
        api_host: "{{ inventory_hostname }}"
        name: "{{ vm_name }}"
        node: home
        state: started
        timeout: 500
      register: result
      until: result is success
      retries: 5
      delay: 10