- name: Proxmox deploy VM
  hosts: all  
  tasks:
    - name: Check if template parameter is defined and not empty
      assert:
        that:
          - template is defined
          - template | length > 0
        fail_msg: "template is mandatory and cannot be empty. try again with parameter -e template=<template_name> on the ansible-playbook command"
      when: template is not defined or template | length == 0

    - set_fact:
        vm_name: "{{ template }}-instance-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=2') }}"

    - name: create vm
      proxmox_kvm:
        api_user    : "{{ ansible_user }}"
        api_password: "{{ ansible_password }}"
        api_host    : "{{ inventory_hostname }}"
        clone       : "{{ template }}"  # The VM source
        name        : "{{ vm_name }}"  # The target VM name
        node        : home
        storage     : local-lvm
        format      : qcow2
        timeout     : 500  # Note: The task can take a while. Adapt depending on the time it takes to clone the VM.

    - name: start vm
      proxmox_kvm:
        api_user: "{{ ansible_user }}"
        api_password: "{{ ansible_password }}"
        api_host: "{{ inventory_hostname }}"
        name: "{{ vm_name }}"
        node: home
        state: started
        timeout: 500
      register: result
      until: result is success
      retries: 5
      delay: 10

    - name: get vm id
      shell: qm list | grep "{{ vm_name }}" | awk '{ print $1 }'
      register: vm_id

    - name: get vm info
      shell: qm config "{{ vm_id.stdout }}" | grep ^net0 | awk -F, '{print $1}' | awk -F= '{print $2}'
      register: vm_info

    - name: get arp
      shell: nmap -sS -T5 "{{ network_address }}"
      register: nmap

    - name: get ip
      shell: arp | grep "{{ vm_info.stdout|lower | regex_replace('^\\/|\\/$', '') }}" | awk '{ print $1 }'
      register: vm_ip
    
    - name: show vm info
      debug:
        msg:
          Server: "{{ vm_name }}"
          ID: "{{ vm_id.stdout }}"
          IP ADDRESS: "{{ vm_ip.stdout}}"
      ignore_errors: true